table pos_ph_data_01
	lineageTag: 652a95fc-f7e4-447f-97d1-03db6de73446

	column period_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b2184831-a36d-4618-9f18-ff7037b62b50
		summarizeBy: none
		sourceColumn: period_end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Customer
		dataType: string
		lineageTag: e40f35fd-0711-497c-a49a-d9f2030e03b2
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: c7404f3f-e0c8-4656-a981-e4d7ccffcc81
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 71585d3f-fde8-453e-9ecd-aaff12d88b2f
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: ef5c4759-165a-4850-b517-ebddef8e6f54
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 51c15d26-634c-4737-b1f4-009268ae7833
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Item_GTIN
		dataType: string
		isHidden
		lineageTag: 926629a1-a320-4765-ac82-60531364b60d
		summarizeBy: none
		sourceColumn: Item_GTIN

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: b229f1bc-034b-48bc-b728-88b4675dd108
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 9d08d798-1613-4069-8cb5-064e3c692b58
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Product_Name
		dataType: string
		lineageTag: af1693ef-2d28-4a7f-82e7-85a08d152e35
		summarizeBy: none
		sourceColumn: Product_Name

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: a0b435b4-6147-4b15-8dd7-7a96109196f3
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column data_provider_key
		dataType: string
		lineageTag: ef7808ee-664a-4d0a-825f-20ee8634aae1
		summarizeBy: none
		sourceColumn: data_provider_key

		annotation SummarizationSetBy = Automatic

	column data_provider_name
		dataType: string
		lineageTag: 7f624e9e-017a-49c9-8f7a-4401fd33fd37
		summarizeBy: none
		sourceColumn: data_provider_name

		annotation SummarizationSetBy = Automatic

	column data_provider_type
		dataType: string
		lineageTag: 745546cc-5004-4759-8bc6-a33c7891d769
		summarizeBy: none
		sourceColumn: data_provider_type

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: f4e1ba4e-9642-4954-ace5-f7f928e9122f
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: double
		lineageTag: 5ae93818-08a0-4268-a19c-64aabf5d8afb
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Key
		dataType: string
		lineageTag: 0836b5d3-38af-4f74-939d-1a1812050a52
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Sales_MSU
		dataType: double
		lineageTag: b7db84ce-4a74-45ca-be9e-fb924059d6a7
		summarizeBy: sum
		sourceColumn: Sales_MSU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BrandForm
		dataType: string
		lineageTag: ffd05200-b46a-4207-b067-ba473fc0facf
		summarizeBy: none
		sourceColumn: BrandForm

		annotation SummarizationSetBy = Automatic

	column Attribute1
		dataType: string
		lineageTag: 8c6a1545-a3e7-4777-ac9c-20730b6af5d8
		summarizeBy: none
		sourceColumn: Attribute1

		annotation SummarizationSetBy = Automatic

	column Attribute2
		dataType: string
		lineageTag: adfa3380-37f3-45f8-b221-044b4d655d19
		summarizeBy: none
		sourceColumn: Attribute2

		annotation SummarizationSetBy = Automatic

	partition pos_ph_data_01 = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Databricks.Catalogs("adb-6342212884588594.14.azuredatabricks.net", "/sql/1.0/warehouses/963202ff1d6a9955", [Catalog="dap_hc_01_dev", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", MetricViewBiCompatibilityMode=null]){[Name="dap_hc_01_dev",Kind="Database"]}[Data], "select * from dap_hc_01_dev.gold_orbis.pos_ph_data_01", null, [EnableFolding=true]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"P&G","Procter & Gamble",Replacer.ReplaceText,{"Company"}),
				    #"Trimmed Text" = Table.TransformColumns(#"Replaced Value",{{"Customer", Text.Trim, type text}, {"Company", Text.Trim, type text}, {"Category", Text.Trim, type text}, {"Brand", Text.Trim, type text}, {"Type", Text.Trim, type text}, {"Channel", Text.Trim, type text}, {"Segment", Text.Trim, type text}, {"Product", Text.Trim, type text}, {"data_provider_type", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Customer", Text.Upper, type text}, {"Company", Text.Upper, type text}, {"Category", Text.Upper, type text}, {"Brand", Text.Upper, type text}, {"Type", Text.Upper, type text}, {"Channel", Text.Upper, type text}, {"Segment", Text.Upper, type text}, {"Product", Text.Upper, type text}, {"data_provider_type", Text.Upper, type text}}),
				    #"Added Key" = Table.AddColumn(#"Uppercased Text", "Key", each Text.Combine(List.Select({[data_provider_type], [Type], [Channel], [Customer], [Category], [Segment], [Brand], [Product]}, each _ <> null and _ <> ""), " - "), type text)
				in
				    #"Added Key"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

