table rtdx_ph_data_01
	lineageTag: 331ca36e-cd34-40a8-9553-05fa1c5f1865

	column time_period_end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b76103a2-3a4c-40a2-9f4d-8ba400eae6ff
		summarizeBy: none
		sourceColumn: time_period_end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column data_provider_key
		dataType: string
		lineageTag: ef708cdc-3c4b-4eff-a75c-163aec04adb7
		summarizeBy: none
		sourceColumn: data_provider_key

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 2f9e7ff9-e152-450f-bc46-32e5a72b4bd9
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: fb67d3d9-2f42-4a84-9332-8ee134e5ab6a
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 13e95add-0f46-4bc1-9715-5a3b06e0fead
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 9e8261eb-b402-4d97-8c4c-d651a2979aa2
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 4fb2f052-1db7-4d9f-9fa4-8e4fd8e443d6
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 24e6ab7d-9d7f-4bb8-888b-3c4de21a9bdb
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Item_GTIN
		dataType: string
		lineageTag: c3a012e7-f4a3-4ed2-951f-3f99bd1fc1d1
		summarizeBy: none
		sourceColumn: Item_GTIN

		annotation SummarizationSetBy = Automatic

	column data_provider_type
		dataType: string
		lineageTag: e223f17c-8444-40f8-b5b6-4fc42a3545e8
		summarizeBy: none
		sourceColumn: data_provider_type

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: 1f3be575-bef4-49e2-851f-836020f5ab7b
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 29dbfaab-28f9-43fb-83bb-49815f62b962
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Units_Sold
		dataType: double
		lineageTag: 2aa56345-79ad-4432-a725-4975606624e2
		summarizeBy: sum
		sourceColumn: Units_Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 2a81e1f5-8468-4aef-afd3-638c9ffb3a4a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Key
		dataType: string
		lineageTag: 292df436-29aa-4b35-b458-bf991cdef7d8
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Sales_MSU
		dataType: double
		lineageTag: a9e242ed-de4f-42e2-a896-6ee92ab48eba
		summarizeBy: sum
		sourceColumn: Sales_MSU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column site_banner_name
		dataType: string
		lineageTag: 63cc8060-3c9b-4c90-bd66-15ca000d115a
		summarizeBy: none
		sourceColumn: site_banner_name

		annotation SummarizationSetBy = Automatic

	column BrandForm
		dataType: string
		lineageTag: 5646fbb7-b481-4401-8fb4-3d666e0f098f
		summarizeBy: none
		sourceColumn: BrandForm

		annotation SummarizationSetBy = Automatic

	column Attribute1
		dataType: string
		lineageTag: 9089f1ad-f924-43bc-a9ef-84526d51ba1b
		summarizeBy: none
		sourceColumn: Attribute1

		annotation SummarizationSetBy = Automatic

	column Attribute2
		dataType: string
		lineageTag: ffe92c03-ce2d-4df5-a574-6b6b5850b302
		summarizeBy: none
		sourceColumn: Attribute2

		annotation SummarizationSetBy = Automatic

	column Latest_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 54000d0c-9105-4bd1-b23f-1f14438ae3a5
		summarizeBy: none
		sourceColumn: Latest_date

		variation Variation
			isDefault
			relationship: 8bbad6ef-25c2-4eaa-8d11-0639726538c7
			defaultHierarchy: LocalDateTable_e65cf1cb-0382-4716-a694-a98c373301f4.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition rtdx_ph_data_01 = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Databricks.Catalogs("adb-6342212884588594.14.azuredatabricks.net", "/sql/1.0/warehouses/963202ff1d6a9955", [Catalog="dap_hc_01_dev", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", MetricViewBiCompatibilityMode=null]){[Name="dap_hc_01_dev",Kind="Database"]}[Data], "select * from dap_hc_01_dev.gold_orbis.rtdx_ph_data_01", null, [EnableFolding=true]),
				    #"Trimmed Text" = Table.TransformColumns(Source,{{"Customer", Text.Trim, type text}, {"Channel", Text.Trim, type text}, {"Company", Text.Trim, type text}, {"Category", Text.Trim, type text}, {"Brand", Text.Trim, type text}, {"Type", Text.Trim, type text}, {"data_provider_type", Text.Trim, type text}, {"Product", Text.Trim, type text}, {"Segment", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Customer", Text.Upper, type text}, {"Channel", Text.Upper, type text}, {"Company", Text.Upper, type text}, {"Category", Text.Upper, type text}, {"Brand", Text.Upper, type text}, {"Type", Text.Upper, type text}, {"data_provider_type", Text.Upper, type text}, {"Product", Text.Upper, type text}, {"Segment", Text.Upper, type text}}),
				    #"Added Key" = Table.AddColumn(#"Uppercased Text", "Key", each Text.Combine(List.Select({[data_provider_type], [Type], [Channel], [Customer], [Category], [Segment], [Brand], [Product]}, each _ <> null and _ <> ""), " - "), type text)
				in
				    #"Added Key"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

