table shipmenets_ph_data_01
	lineageTag: 04d85ddd-9380-474b-8337-65d0687d6ae9

	column DataType
		dataType: string
		lineageTag: 39baae18-e867-442d-91fd-21a1fecc6388
		summarizeBy: none
		sourceColumn: DataType

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: f90699f0-3e32-4bd6-adc6-b5f810f6acf1
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 417686e2-2828-420c-bd46-545ca136ba22
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: ea76e87e-b7b2-41c3-9826-d52f4e746e85
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: cdeb14a3-8df1-46f1-b5af-920c5b62de43
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: ed91200e-d865-4b39-9dfa-b521a8c5c2dc
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: ed9bcf32-c16f-413d-9ec0-2c3a3d41874f
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column Order_No
		dataType: string
		lineageTag: 1215a48e-c4e6-401d-959c-143d2c461a75
		summarizeBy: none
		sourceColumn: Order_No

		annotation SummarizationSetBy = Automatic

	column Invoice_No
		dataType: string
		lineageTag: 84acb7a8-535b-49f6-8ad2-81f1c57e5933
		summarizeBy: none
		sourceColumn: Invoice_No

		annotation SummarizationSetBy = Automatic

	column Deliver_No
		dataType: string
		lineageTag: 16f4c802-73cd-47dd-a8e5-508219367086
		summarizeBy: none
		sourceColumn: Deliver_No

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: cba93161-bb11-4500-8032-1dcc02c22aae
		summarizeBy: none
		sourceColumn: Order_Date

		variation Variation
			isDefault
			relationship: c5b0f9f8-1b32-430a-99cc-429e8e18982a
			defaultHierarchy: LocalDateTable_acb7e0f5-8c39-4285-8c1b-f7db9bf98096.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Delivery_Creation_Date
		dataType: string
		lineageTag: b8fda372-08f8-4929-9243-0c42e098841a
		summarizeBy: none
		sourceColumn: Delivery_Creation_Date

		annotation SummarizationSetBy = Automatic

	column GI_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2c2e2d77-fe5b-48cd-8938-c6972ba49970
		summarizeBy: none
		sourceColumn: GI_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Requested_Delivery_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0649bef4-7211-40fa-9fac-a1fc7566236e
		summarizeBy: none
		sourceColumn: Requested_Delivery_Date

		variation Variation
			isDefault
			relationship: 413449e4-ecea-4297-b8b7-4c368fea90d3
			defaultHierarchy: LocalDateTable_7049c086-3eda-424b-9dae-14f30d26f89d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Pricing_Date
		dataType: string
		lineageTag: 240a6512-2549-4cdf-97ed-a499fa7c10e5
		summarizeBy: none
		sourceColumn: Pricing_Date

		annotation SummarizationSetBy = Automatic

	column Sold_To
		dataType: string
		lineageTag: d8ddbd9e-12d3-4111-9af7-feb07994e1cb
		summarizeBy: none
		sourceColumn: Sold_To

		annotation SummarizationSetBy = Automatic

	column Sold_To_Name
		dataType: string
		lineageTag: aa46abeb-e263-4b3a-8c72-fa485120a6b7
		summarizeBy: none
		sourceColumn: Sold_To_Name

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 299118a2-ff97-46a1-99a6-15cf3271e99a
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 3d4e327b-aedd-4e7a-8e46-6bf026958831
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Item_gtin
		dataType: string
		lineageTag: cb0a1e09-0535-42e8-9358-59e1ac12fb2a
		summarizeBy: none
		sourceColumn: Item_gtin

		annotation SummarizationSetBy = Automatic

	column Product_name
		dataType: string
		lineageTag: 14c91324-694c-4565-a85f-9206eb0b8807
		summarizeBy: none
		sourceColumn: Product_name

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: string
		lineageTag: d56fd40d-dd34-4737-a85f-5c1d5ba6af9e
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = Automatic

	column Order_Qty
		dataType: double
		lineageTag: f718e3c4-1c2d-4ccc-bd58-7bbe5f7076ac
		summarizeBy: sum
		sourceColumn: Order_Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Qty_SU
		dataType: double
		lineageTag: 03dd45f7-25b9-488c-a6b7-55f212fd6eb4
		summarizeBy: sum
		sourceColumn: Order_Qty_SU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Qty_MSU
		dataType: double
		lineageTag: 8b751c07-047d-4cbc-b6c1-7ea2ec481ec8
		summarizeBy: sum
		sourceColumn: Order_Qty_MSU

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NIV
		dataType: double
		lineageTag: 99f2d6cb-8e94-4e1e-91c6-ca6985579848
		summarizeBy: sum
		sourceColumn: NIV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GIV
		dataType: double
		lineageTag: b66b88b8-e520-4401-9c19-c982282fe114
		summarizeBy: sum
		sourceColumn: GIV

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Status_Desc
		dataType: string
		lineageTag: d0a6c4f2-f23f-466c-bff3-c7616831327f
		summarizeBy: none
		sourceColumn: Order_Status_Desc

		annotation SummarizationSetBy = Automatic

	column Key
		dataType: string
		lineageTag: 8163e23c-f6b3-4410-84ce-3f5c2fb072ab
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column BrandForm
		dataType: string
		lineageTag: f88cb9b4-d78f-417e-8a4e-4b37d2634c19
		summarizeBy: none
		sourceColumn: BrandForm

		annotation SummarizationSetBy = Automatic

	column Attribute1
		dataType: string
		lineageTag: 1ec1436e-0f86-43f4-a204-410b06c5a348
		summarizeBy: none
		sourceColumn: Attribute1

		annotation SummarizationSetBy = Automatic

	column Attribute2
		dataType: string
		lineageTag: 3114b7f7-c82a-49a0-ade1-57d2ea3e3078
		summarizeBy: none
		sourceColumn: Attribute2

		annotation SummarizationSetBy = Automatic

	partition shipmenets_ph_data_01 = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Databricks.Catalogs("adb-6342212884588594.14.azuredatabricks.net", "/sql/1.0/warehouses/963202ff1d6a9955", [Catalog="dap_hc_01_dev", Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", MetricViewBiCompatibilityMode=null]){[Name="dap_hc_01_dev",Kind="Database"]}[Data], "select * from dap_hc_01_dev.gold_orbis.shipmenets_ph_data_01", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"GI_Date", type date}, {"Order_Date", type date}, {"Requested_Delivery_Date", type date}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Changed Type",{{"Order_No", Text.Trim, type text}, {"Category", Text.Trim, type text}, {"Company", Text.Trim, type text}, {"Brand", Text.Trim, type text}, {"Type", Text.Trim, type text}, {"DataType", Text.Trim, type text}, {"Product", Text.Trim, type text}, {"Segment", Text.Trim, type text}, {"Customer", Text.Trim, type text}, {"Channel", Text.Trim, type text}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Trimmed Text",{{"Order_No", Text.Upper, type text}, {"Category", Text.Upper, type text}, {"Company", Text.Upper, type text}, {"Brand", Text.Upper, type text}, {"Type", Text.Upper, type text}, {"DataType", Text.Upper, type text}, {"Product", Text.Upper, type text}, {"Segment", Text.Upper, type text}, {"Customer", Text.Upper, type text}, {"Channel", Text.Upper, type text}}),
				    Custom1 = Table.AddColumn(#"Uppercased Text", "Key", each Text.Combine(List.Select({[DataType], [Type], [Channel], [Customer], [Category], [Segment], [Brand], [Product]}, each _ <> null and _ <> ""), " - "), type text)
				in
				    Custom1

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

