table 'Time Period'
	lineageTag: 3c7c03c0-4ced-4e91-bb00-f70251e6e098

	column Period
		dataType: string
		lineageTag: e5fb982b-2755-4a7e-869d-61695a1e203a
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: Rank

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Rank
		dataType: int64
		formatString: 0
		lineageTag: 66c0f65d-a518-464a-9ccb-312e889a90f2
		summarizeBy: sum
		sourceColumn: Rank

		annotation SummarizationSetBy = Automatic

	partition 'Time Period' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCk7NSU0uSU1R8M3PK8lQ0lEyUIrViVYKMPQFsg0hbGMQ2xjCNgOxzaBqjMCKjMA8t8gQFxAPoi4QwjEBc3whHFOl2FgA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Period = _t, Rank = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Period", type text}, {"Rank", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

